[package]
name = "iwpo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = "0.8.9"
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"